### PR TITLE
completed http-messages-recap

### PR DESCRIPTION
**Pull request by Quintin-Russell**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Were you not able to do this in your dev environment terminal?

**Comment by Quintin-Russell** [comment]
i was not able to see the response

**Comment by TimelikeClosure** [comment]
It worked the first time around: https://github.com/Quintin-Russell/m2-0621-code-solutions/pull/10

Have you changed dev environments since then? More importantly, the http://httpie.io website doesn't have access to your local file system, so it can't create the files that should have been created as part of the exercise.

**Comment by Quintin-Russell** [comment]
image

**Review by TimelikeClosure — APPROVED** [review]

**Pull request merged**
